### ISSUE TITLE
 Request for Code and Minimum Hardware Requirements

### ISSUE THREAD

**Issue by wyy511511** [WinKawaks/DreamWire#7]
I have implemented a version of your work based on your paper but am struggling to achieve the demo results. Could you please share the implementation code and the minimum hardware requirements to run it?
Thanks!

**Comment by jsammarco** [comment]
Good luck. They aren't sharing the code. :(

**Comment by WinKawaks** [comment]
@wyy511511 I will release the code after CVPR. I ran all experiments with a single A100 (80G) and fp32. With fp16, I think a 3090 is OK. As the loss function is the sum of SDS loss of all perspectives, there may be 2 losses that are decreasing and one that is going up, but the sum is still decreasing. So the generated results are hardly perfect, which is also why MVWA is so difficult to design. A useful trick is randomly initialising the curves with larger numbers (64) and segments (5) and rearranging short strokes at each stage.

**Comment by yosun** [comment]
what are your inference times on an a100? 

why not put the model on replicate.com or huggingface? (these are also linked on the arxiv listing)

**Comment by qzyhaq** [comment]
@yosun @jsammarco @wyy511511 The biggest characteristic of winkawaks is that he never tells the truth. His work experience at LinkedIn is fake, and his two girlfriends at home and abroad don't know each other. His code cannot be reliable

**Comment by ugotsoul** [comment]
@WinKawaks are you planning on sharing any of the code?

**Comment by jsammarco** [comment]
> @WinKawaks are you planning on sharing any of the code?

I second this. Please release the code!
